services:
  - type: web
    name: django-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn gestion_vehicules.wsgi:application --log-file -
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: gestion_vehicules.settings
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com 